release: Ensure crate version matches release tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -19,7 +19,43 @@ permissions:
   contents: read
 
 jobs:
+  meta:
+    timeout-minutes: 5
+    runs-on: ubuntu-latest
+    container:
+      image: docker://rust:1.60-bullseye
+    steps:
+      - id: meta
+        shell: bash
+        run: |
+          ref="${{ github.ref }}"
+          if [[ "$ref" == refs/tags/release/* ]]; then
+            echo ::set-output name=version::"${ref##refs/tags/release/}"
+            echo ::set-output name=mode::release
+          else
+            sha="${{ github.sha }}"
+            echo ::set-output name=version::"test-${sha:0:7}"
+            echo ::set-output name=mode::test
+          fi
+      - if: steps.meta.outputs.mode == 'release'
+        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
+      - if: steps.meta.outputs.mode == 'release'
+        shell: bash
+        run: |
+          curl --proto '=https' --tlsv1.3 -fsSL https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o $HOME/jq
+          chmod 755 $HOME/jq
+          version=$(cargo metadata --format-version=1 | $HOME/jq -r '.packages[] | select(.name == "hokay") | .version')
+          if [[ "v${version}" != "${{ steps.meta.outputs.version }}" ]]; then
+            echo "::error ::Crate version v${version} does not match tag ${{ steps.meta.outputs.version }}"
+            exit 1
+          fi
+    outputs:
+      repo: ghcr.io/${{ github.repository_owner }}/hokay
+      mode: ${{ steps.meta.outputs.mode }}
+      version: ${{ steps.meta.outputs.version }}
+
   package:
+    needs: [meta]
     strategy:
       matrix:
         architecture: [amd64, arm64, arm]
@@ -73,24 +109,12 @@ jobs:
 
   # Publish a multi-arch docker image using the already-built binaries..
   docker:
-    needs: [package]
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
+    needs: [meta, package]
     permissions:
       packages: write
+    timeout-minutes: 5
+    runs-on: ubuntu-latest
     steps:
-      - name: Meta
-        id: meta
-        run: |
-          repo="ghcr.io/${{ github.repository_owner }}/hokay"
-          ref="${{ github.ref }}"
-          echo ::set-output name=repo::"$repo"
-          if [[ "$ref" == refs/tags/release/* ]]; then
-            echo ::set-output name=version::"${ref##refs/tags/release/}"
-          else
-            sha="${{ github.sha }}"
-            echo ::set-output name=version::"test-${sha:0:7}"
-          fi
       - name: Run mktemp
         id: mktemp
         run: echo ::set-output name=dir::"$(mktemp -d -t hokay-XXXXXX)"
@@ -111,8 +135,8 @@ jobs:
             echo 'COPY $BIN /hokay'
             echo 'ENTRYPOINT ["/hokay"]'
           ) >Dockerfile
-          repo="${{ steps.meta.outputs.repo }}"
-          version="${{ steps.meta.outputs.version }}"
+          repo="${{ needs.meta.outputs.repo }}"
+          version="${{ needs.meta.outputs.version }}"
           for arch in amd64 arm64 arm; do
             docker buildx build . --push --tag "$repo:$version-$arch" --build-arg "BIN=artifacts/$arch-artifacts/hokay-$arch"
           done
@@ -120,8 +144,8 @@ jobs:
           for arch in amd64 arm64 arm ; do
             docker manifest annotate "$repo:$version" "$repo:$version-$arch" --os=linux --arch=$arch
           done
-      - run: docker manifest push "${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.version }}"
-      - if: startsWith(github.ref, 'refs/tags/release/')
+      - run: docker manifest push "${{ needs.meta.outputs.repo }}:${{ needs.meta.outputs.version }}"
+      - if: needs.meta.outputs.mode == 'release'
         run: |
           repo="${{ steps.meta.outputs.repo }}"
           version="${{ steps.meta.outputs.version }}"
@@ -131,12 +155,12 @@ jobs:
 
   # Publish a GitHub release with platform-specific static binaries.
   release:
-    if: startsWith(github.ref, 'refs/tags/release/')
-    needs: [package, docker]
-    runs-on: ubuntu-latest
-    timeout-minutes: 5
+    needs: [meta, package, docker]
+    if: needs.meta.outputs.mode == 'release'
     permissions:
       contents: write
+    timeout-minutes: 5
+    runs-on: ubuntu-latest
     steps:
       - name: meta
         id: meta
@@ -148,16 +172,16 @@ jobs:
           path: artifacts
       - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
         with:
-          name: ${{ steps.meta.outputs.name }}
+          name: ${{ needs.meta.outputs.version }}
           files: artifacts/**/hokay-*
           generate_release_notes: true
 
   # If the release was skipped, list the built binaries.
   list:
-    if: "!startsWith(github.ref, 'refs/tags/release/')"
-    needs: [package]
-    runs-on: ubuntu-latest
+    needs: [meta, package]
+    if: needs.meta.outputs.mode == 'test'
     timeout-minutes: 5
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
         with:
